### ISSUE TITLE
PHP is bad

### ISSUE THREAD

**Issue by wuxishy** [tjsct/sct-website-python#1]
Please remove all traces of PHP badness.

**Comment by gengkev** [comment]
here is the problem:
1. we should try not to break existing links (so we will have to set up a 301 for the .php urls)
2. the current nginx configuration will redirect a url without a file extension such as `/lectures` to `/lectures/` which is not what we want

**Comment by wuxishy** [comment]
wait, can I see the current nginx configuration?

**Comment by gengkev** [comment]
I do not know what it is... I assume it's the configuration for director that's doing it, so you should ask eric
